/*!
 * mgGlitch : little jquery helper to glitch everything
 * (c) 2016 Hadrien Mongouachon
 * MIT Licensed.
 *
 * Author URI: http://hmongouachon.com
 * Plugin URI: http://hmongouachon.com

 * Version: 1.0.0
 */
!function(t,s,i,e){"use strict";var n={destroy:!1,glitch:!0,scale:!0,blend:!0,blendModeType:"hue",glitch1TimeMin:600,glitch1TimeMax:900,glitch2TimeMin:10,glitch2TimeMax:115,zIndexStart:5};function r(s,i){this.element=s,this.settings=t.extend({},n,i),this._defaults=n,this._name="mgGlitch",this.init()}t.extend(r.prototype,{init:function(){this.glitch()},glitch:function(){var s=this.element,i=this.settings.scale,e=this.settings.glitch1TimeMin,n=this.settings.glitch1TimeMax,r=this.settings.glitch2TimeMin,a=this.settings.glitch2TimeMax,l=this.settings.zIndexStart;function c(t,s){return Math.floor(Math.random()*(s-t+1))+t}if(!0===this.settings.destroy)(t(s).siblings().hasClass("el-front-1")||t(s).siblings().hasClass("front-3")||t(s).siblings().hasClass("front-2"))&&t(s).siblings(".front-1, .front-2, .front-3").remove(),t(".back").removeClass("back");else if(!1===this.settings.destroy){if(t(s).clone().insertBefore(s).addClass("back").css({"z-index":l}),!0===this.settings.blend)t(s).clone().insertAfter(s).addClass("front-3").css({"z-index":l+3,"mix-blend-mode":this.settings.blendModeType}),function e(){var n=c(10,1900),l=c(10,1300),o=c(0,40),h=c(0,40),f=c(r,a);if(!0===i)var d=(Math.random()*(1.1-.9)+.9).toFixed(2);else if(!1===i)d=1;t(s).next().next().css({clip:"rect("+n+"px, 9999px, "+l+"px,0px)",left:o,right:h,"-webkit-transform":"scale("+d+")","-ms-transform":"scale("+d+")",transform:"scale("+d+")"}),setTimeout(e,f)}();if(!0===this.settings.glitch)t(s).clone().insertAfter(s).addClass("front-2").css({"z-index":l+2}),t(".back").next().addClass("front-1").css({"z-index":l+1}),function i(){var r=c(10,1900),a=c(10,1300),l=c(0,16),o=c(0,16),h=c(e,n);t(s).css({clip:"rect("+r+"px, 9999px, "+a+"px,0px)",right:o,left:l}),setTimeout(i,h)}(),function e(){var n=c(10,1900),l=c(10,1300),o=c(0,40),h=c(0,40),f=c(r,a);if(!0===i)var d=(Math.random()*(1.1-.9)+.9).toFixed(2);else if(!1===i)d=1;t(s).next().css({clip:"rect("+n+"px, 9999px, "+l+"px,0px)",left:o,right:h,"-webkit-transform":"scale("+d+")","-ms-transform":"scale("+d+")",transform:"scale("+d+")"}),setTimeout(e,f)}()}}}),t.fn.mgGlitch=function(t){return this.each((function(){new r(this,t)}))}}(jQuery,window,document);